### ISSUE TITLE
API.get_user() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by alijnmerchant21** [alijnmerchant21/twitter-bot-follower#1]
Traceback (most recent call last):
  File "/Users/aliasgarmerchant/Desktop/projects/twitter-bot-follower/bot.py", line 64, in <module>
    user = api.get_user(follower_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: API.get_user() takes 1 positional argument but 2 were given

**Comment by alijnmerchant21** [comment]
I added print statement in code to check what is being passed as `follower_id.` It is a single argument. Not clear why it keeps throwing this error.

**Comment by alijnmerchant21** [comment]
**Solution**

From [Tweepy API Documentation](https://docs.tweepy.org/en/stable/getting_started.html#api) `get_user` should be passed `id` as `api.get_user(user_id=follower_id)`
